---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  ansible.netcommon: ">=1.3.0"
description: Community yang Collection for yang based operation
license_file: LICENSE
name: yang
namespace: community
readme: README.md
repository: https://github.com/ansible-collections/community.yang
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
version: "1.2.0"
